<?php

/**
 * @file
 * Provides Views Implementation for Islandora Solr
 */

/**
 * Implements hook_views_api().
 */
function islandora_solr_views_views_api() {
  return array('api' => '3.0');
}

function islandora_solr_views_get_field_values($fieldname) {
  $params = array(
    'facet' => 'true',
    'facet.field' => array($fieldname),
    'facet.mincount' => 1,
    'facet.limit' => -1,
  );
  $solr_build = new IslandoraSolrQueryProcessor();
  $solr_build->buildQuery(format_string("!fieldname:*", array(
    '!fieldname' => $fieldname,
  )), $params);
  $solr_build->solrParams = islandora_solr_remove_base_filters($solr_build->solrParams);
  $solr_build->solrParams = array_replace($solr_build->solrParams, $params);
  $solr_build->solrLimit = 0;
  $solr_build->executeQuery(FALSE);
  $values = array();
  if (isset($solr_build->islandoraSolrResult['facet_counts']['facet_fields'][$fieldname])) {
    foreach ($solr_build->islandoraSolrResult['facet_counts']['facet_fields'][$fieldname] as $value => $count) {
      if (!empty($value)) {
        $values[] = trim($value);
      }
    }
  }
  return $values;
}
